pipeline {
    agent any

    environment {
        REGION =  "us-east-1"
    }

    tools {
        maven 'maven3.8.6'
        jdk 'jdk11'
    }
    stages {

        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage('Build')  {
            steps {
                sh 'mvn -B -DskipTests clean package -U'
            }
        }

        stage  ('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/**/*.xml'
                }
            }
        }

        stage ('Deploy-Dev-Infrastructure') {
            steps {
                sh """
                    # Development web server

                    aws cloudformation deploy \
                    --stack-name dev-web \
                    --template-file ./infrastructure/web/web-root-dev.yaml \
                    --capabilities CAPABILITY_IAM \
                    --region ${REGION} \
                    --no-fail-on-empty-changeset
                """
            }
        }

        stage ('Deploy') {
            steps {
                deploy adapters: [
                    tomcat9(
                        credentialsId: 'admin',
                        path: '',
                        url: 'http://44.211.110.219:8080/'
                    )
                ], contextPath: '', war: '**/*.war'
            }
        }
    }
}