Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue user-management-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - LabRole

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SQL access to the DB
      VpcId: !ImportValue user-management-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt WebServerSecurityGroup.GroupId


Outputs:

  DBSecurityGroup:
    Description: a ref to db sec group
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-dbsecuritygroup"
    
  WebServerSecurityGroup:
    Description: A reference to the web server's security group
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-WebServerSecurityGroup"

  WebEC2InstanceProfile:
    Description: A reference to the web server's instance profile
    Value: !Ref WebEC2InstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-WebEC2InstanceProfile"