Parameters:
  
  InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Type: String
    Default: vockey

  Stage:
    Type: String
    Default: dev

Resources:

  WebServerNode1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0b898040803850657
      KeyName: !Ref KeyName
      IamInstanceProfile: !ImportValue user-management-security-WebEC2InstanceProfile
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
              yum update -y
              yum install -y tomcat
              yum install -y tomcat-webapps
              yum install -y tomcat-admin-webapps
              echo Stack="${AWS::StackName}" >> /usr/share/tomcat/conf/tomcat.conf
              aws s3api get-object --bucket tomcat-config-jhopwood --key tomcat_users_2_.xml /usr/share/tomcat/conf/tomcat-users.xml
              service tomcat start
              systemctl enable tomcat.service
      SecurityGroupIds:
        - !ImportValue user-management-security-WebServerSecurityGroup
      SubnetId: !ImportValue user-management-vpc-PublicSubnet1
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"

  # This is like deprecated or something. EIP technically isn't a real property
  # Run it anyway, and it should work. Ignore cfn-lint
  WebEIP:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref WebServerNode1
      EIP:
        Fn::ImportValue:
          Fn::Sub: "WebEIP-user-management-ip-${Stage}"

Outputs:
  
  WebServerURL:
    Description: URL to acces our Tomcat Server
    Value: !Join [ "", [ "http://", !GetAtt WebServerNode1.PublicIp, ":8080"] ]
    Export:
      Name: !Sub "${AWS::StackName}-TomcatURL"
        