Parameters:
  
  InstanceType:
    Type: String

  KeyName:
    Type: String

  ImageId:
    Type: String
  
  WebEC2InstanceProfile:
    Type: String

  WebEIP: 
    Type: String
  
  PublicSubnet1:
    Type: String

  WebServerSecurityGroup:
    Type: String  

Resources:

  # bucket name with the tomcat users file was changed to tomcat-config-jhopwood1 (appended a 1) to satisfy global unique name
  # requirements due to it already existing in the other learner lab.
  WebServerNode1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref WebEC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y tomcat
          yum install -y tomcat-webapps
          yum install -y tomcat-admin-webapps
          echo Stack="${AWS::StackName}" >> /usr/share/tomcat/conf/tomcat.conf
          aws s3api get-object --bucket tomcat-config-jhopwood1 --key tomcat_users_2_.xml /usr/share/tomcat/conf/tomcat-users.xml
          service tomcat start
          systemctl enable tomcat.service
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"

  # This is like deprecated or something. EIP technically isn't a real property
  # Run it anyway, and it should work. Ignore cfn-lint
  WebEIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref WebServerNode1
      EIP: !Ref WebEIP

Outputs:
  
  WebServerURL:
    Description: URL to acces our Tomcat Server
    Value: !Join [ "", [ "http://", !GetAtt WebServerNode1.PublicIp, ":8080"] ]
    Export:
      Name: !Sub "${AWS::StackName}-TomcatURL"
        