Parameters:

  JenkinsEIP:
    Type: String

  JenkinsInstanceProfile:
    Type: String

  JenkinsSecurityGroup:
    Type: String

  InstanceType:
    Type: String
 
  KeyName:
    Type: String
  
  ImageId:
    Type: String

  Name:
    Type: String

Resources:

  JenkinsServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName:  !Ref KeyName
      IamInstanceProfile: !Ref JenkinsInstanceProfile
      SecurityGroupIds:
         - !Ref JenkinsSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref Name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Exit on error and print commands as they execute
          set -ex

          # Update package lists
          apt-get update -y

          # Install Java (only one version needed - OpenJDK 11 is sufficient)
          apt-get install -y openjdk-11-jdk

          # Setup Jenkins repository (removed duplicate commands)
          curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | \
              sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
              https://pkg.jenkins.io/debian-stable binary/" | \
              sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

          # Install Jenkins
          apt-get update -y
          apt-get install -y jenkins
          systemctl enable --now jenkins

          # Install Maven
          apt-get install -y maven

          # Install AWS CLI
          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          apt-get install -y unzip
          unzip -q awscliv2.zip
          ./aws/install
          rm -rf awscliv2.zip aws

          # Verify installations
          java -version
          jenkins --version
          mvn -v
          aws --version

  JenkinsEIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref JenkinsServer
      EIP: !Ref JenkinsEIP
    
